misc.
GiGGioSo/mkwii-ita-auto-TT-boards pull request #4
Opened 2022-09-09 14:44 UTC by FallBackITA27

2022-09-09 18:43 UTC, GiGGioSo requested changes
Un paio di robe non sono d'accordo, prova a dare un'occhiata.

2022-09-09 18:43 UTC, GiGGioSo commented on src/gui/updater.py
> +            if self.debug_checked: self.display_msg.emit(f"[CHECKING ROW {display_row}] ID: {ID}")
In che modo è più veloce che scrivere row+1

2022-09-09 18:43 UTC, GiGGioSo commented on src/gui/updater.py
> +        display_row = row+1 #Row to display in messages
non voglio creare una variabile solo per questo

2022-09-09 18:43 UTC, GiGGioSo commented on src/gui/updater.py
> +            return -1
il return code -1 rappresenta un'interruzione forzata, quindi qua non ci va

2022-09-09 18:43 UTC, GiGGioSo commented on src/gui/updater.py
> +                full_gs[row+jolly][gs_track_column-1] = "=IMAGE(\"" + cd.get_ghost_mii(g["href"]) + "\")" # Mii image link, taken from chadsoft (run.mii)
run.mii? che vuol dire

2022-09-09 18:43 UTC, GiGGioSo commented on src/gui/updater.py
> +            if self.debug_checked: self.display_msg.emit(f"  [OUTDATED DATA FOUND AT ROW {display_row}] fetching player JSON from Chadsoft...")
la current row viene già printata a riga 77, qua non serve

2022-09-09 18:43 UTC, GiGGioSo commented on src/apis/google_sheet.py
> +    "15B303B288F4707E5D0AF28367C8CE51CDEAB490": [2, 1],      # rBC   (NO-SC/G)
Ma io voglio i nomi interi, non voglio stare a pensare alle abbreviazioni (anche perchè non le so). Piuttosto aggiungile e basta

2022-09-10 10:00 UTC, FallBackITA27 commented on src/gui/updater.py
> +            if self.debug_checked: self.display_msg.emit(f"[CHECKING ROW {display_row}] ID: {ID}")
è solo più clean da leggere, non è più veloce

2022-09-10 10:01 UTC, FallBackITA27 commented on src/gui/updater.py
> +                full_gs[row+jolly][gs_track_column-1] = "=IMAGE(\"" + cd.get_ghost_mii(g["href"]) + "\")" # Mii image link, taken from chadsoft (run.mii)
link della run .mii

2022-09-10 10:02 UTC, FallBackITA27 commented on src/gui/updater.py
> +            if self.debug_checked: self.display_msg.emit(f"  [OUTDATED DATA FOUND AT ROW {display_row}] fetching player JSON from Chadsoft...")
Usando il programma spesso succede che perché scrive dal basso verso l'alto ci si confonde la riga al quale il programma si riferisce, specificare qua è solo meglio, nulla di che

2022-09-10 12:01 UTC, GiGGioSo commented on src/gui/updater.py
> +                full_gs[row+jolly][gs_track_column-1] = "=IMAGE(\"" + cd.get_ghost_mii(g["href"]) + "\")" # Mii image link, taken from chadsoft (run.mii)
quello allora va piuttosto nella documentazione del metodo get ghost mii

2022-09-10 13:14 UTC, FallBackITA27 commented on src/gui/updater.py
> +                full_gs[row+jolly][gs_track_column-1] = "=IMAGE(\"" + cd.get_ghost_mii(g["href"]) + "\")" # Mii image link, taken from chadsoft (run.mii)
Poi lo faccio, poi lo faccio.

2022-09-11 08:08 UTC, GiGGioSo approved these changes
nice

2022-09-11 08:09 UTC, merged